version: 2.1

executors:
  linux:
    docker:
      - image: ethereum/cpp-build-env:11

commands:
  build_and_test:
    description: "Build & Test"
    steps:
      - run:
          name: "Environment"
          command: |
            CC=${CC:-cc}
            CXX=${CXX:-cpp}
            echo CC: $CC
            echo CXX: $CXX
            $CC --version
            $CXX --version
            cmake --version
      - checkout
      - run:
          name: "Update submodules"
          command: git submodule update --init --recursive
      - run:
          name: "Configure"
          working_directory: ~/build
          command: cmake ../project -DCMAKE_INSTALL_PREFIX=~/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DEVMONE_TESTING=ON $CMAKE_OPTIONS
      - run:
          name: "Build"
          command: cmake --build ~/build -- -j4
      - run:
          name: "Test"
          working_directory: ~/build
          command: ctest -R ${TESTS_FILTER:-'.*'} -j4 --schedule-random --output-on-failure
      - run:
          name: "Install"
          command: cmake --build ~/build --target install

jobs:

  lint:
    docker:
    - image: ethereum/cpp-build-env:11
    steps:
    - checkout
    - run:
        name: "Check code format"
        command: |
          clang-format --version
          find include lib test -name '*.hpp' -o -name '*.cpp' -o -name '*.h' -o -name '*.c' | xargs clang-format -i
          git diff --color --exit-code
    - run:
        name: "Run codespell"
        command: |
          codespell --quiet-level=4

  gcc-min:
    executor: linux
    environment:
      CC: gcc-7
      CXX: g++-7
    steps:
      - build_and_test

  gcc-latest-coverage:
    executor: linux
    environment:
      BUILD_TYPE: Debug
      CC: gcc-8
      CXX: g++-8
      GCOV: gcov-8
      CMAKE_OPTIONS: -DCOVERAGE=ON
      TESTS_FILTER: unittests
    steps:
      - build_and_test
      - run:
          name: "Upload coverage data"
          command: |
            codecov --required --gcov-exec "$GCOV" --gcov-root ~/build

  clang-latest-ubsan:
    executor: linux
    environment:
      CC: clang-8
      CXX: clang++-8
      # Also set visibility to default, because UBSan from clang-8 has issues
      # with comparing pointers to functions. The problem is solved in clang-9.
      CMAKE_OPTIONS: -DSANITIZE=undefined,implicit-conversion,nullability -DCMAKE_CXX_FLAGS=-fvisibility=default
      UBSAN_OPTIONS: halt_on_error=1
    steps:
      - build_and_test

  macos-asan:
    macos:
      xcode: 10.2.0
    environment:
      BUILD_TYPE: RelWithDebInfo
      CMAKE_OPTIONS: -DSANITIZE=address
      TESTS_FILTER: unittests
    steps:
      - run:
          name: "Install System Dependencies"
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake
      - build_and_test

workflows:
  version: 2
  evmone:
    jobs:
      - lint
      - gcc-min
      - gcc-latest-coverage
      - clang-latest-ubsan
      - macos-asan
